// Code generated by ent, DO NOT EDIT.

package memberschema

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the memberschema type in the database.
	Label = "member_schema"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMemberID holds the string denoting the memberid field in the database.
	FieldMemberID = "member_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// EdgeClients holds the string denoting the clients edge name in mutations.
	EdgeClients = "clients"
	// Table holds the table name of the memberschema in the database.
	Table = "member_schemas"
	// ClientsTable is the table that holds the clients relation/edge. The primary key declared below.
	ClientsTable = "client_schema_members"
	// ClientsInverseTable is the table name for the ClientSchema entity.
	// It exists in this package in order to avoid circular dependency with the "clientschema" package.
	ClientsInverseTable = "client_schemas"
)

// Columns holds all SQL columns for memberschema fields.
var Columns = []string{
	FieldID,
	FieldMemberID,
	FieldName,
	FieldPhone,
	FieldEmail,
	FieldRole,
}

var (
	// ClientsPrimaryKey and ClientsColumn2 are the table columns denoting the
	// primary key for the clients relation (M2M).
	ClientsPrimaryKey = []string{"client_schema_id", "member_schema_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "Name" field. It is called by the builders before save.
	NameValidator func(string) error
)

// OrderOption defines the ordering options for the MemberSchema queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMemberID orders the results by the MemberID field.
func ByMemberID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemberID, opts...).ToFunc()
}

// ByName orders the results by the Name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPhone orders the results by the Phone field.
func ByPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhone, opts...).ToFunc()
}

// ByEmail orders the results by the Email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByRole orders the results by the Role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByClientsCount orders the results by clients count.
func ByClientsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newClientsStep(), opts...)
	}
}

// ByClients orders the results by clients terms.
func ByClients(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClientsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newClientsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClientsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, ClientsTable, ClientsPrimaryKey...),
	)
}
