// Code generated by ent, DO NOT EDIT.

package memberschema

import (
	"client_service/internal/infrastructure/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldLTE(FieldID, id))
}

// MemberID applies equality check predicate on the "MemberID" field. It's identical to MemberIDEQ.
func MemberID(v int64) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldEQ(FieldMemberID, v))
}

// Name applies equality check predicate on the "Name" field. It's identical to NameEQ.
func Name(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldEQ(FieldName, v))
}

// Phone applies equality check predicate on the "Phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldEQ(FieldPhone, v))
}

// Email applies equality check predicate on the "Email" field. It's identical to EmailEQ.
func Email(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldEQ(FieldEmail, v))
}

// Role applies equality check predicate on the "Role" field. It's identical to RoleEQ.
func Role(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldEQ(FieldRole, v))
}

// MemberIDEQ applies the EQ predicate on the "MemberID" field.
func MemberIDEQ(v int64) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldEQ(FieldMemberID, v))
}

// MemberIDNEQ applies the NEQ predicate on the "MemberID" field.
func MemberIDNEQ(v int64) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldNEQ(FieldMemberID, v))
}

// MemberIDIn applies the In predicate on the "MemberID" field.
func MemberIDIn(vs ...int64) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldIn(FieldMemberID, vs...))
}

// MemberIDNotIn applies the NotIn predicate on the "MemberID" field.
func MemberIDNotIn(vs ...int64) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldNotIn(FieldMemberID, vs...))
}

// MemberIDGT applies the GT predicate on the "MemberID" field.
func MemberIDGT(v int64) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldGT(FieldMemberID, v))
}

// MemberIDGTE applies the GTE predicate on the "MemberID" field.
func MemberIDGTE(v int64) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldGTE(FieldMemberID, v))
}

// MemberIDLT applies the LT predicate on the "MemberID" field.
func MemberIDLT(v int64) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldLT(FieldMemberID, v))
}

// MemberIDLTE applies the LTE predicate on the "MemberID" field.
func MemberIDLTE(v int64) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldLTE(FieldMemberID, v))
}

// NameEQ applies the EQ predicate on the "Name" field.
func NameEQ(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "Name" field.
func NameNEQ(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "Name" field.
func NameIn(vs ...string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "Name" field.
func NameNotIn(vs ...string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "Name" field.
func NameGT(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "Name" field.
func NameGTE(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "Name" field.
func NameLT(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "Name" field.
func NameLTE(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "Name" field.
func NameContains(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "Name" field.
func NameHasPrefix(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "Name" field.
func NameHasSuffix(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "Name" field.
func NameEqualFold(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "Name" field.
func NameContainsFold(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldContainsFold(FieldName, v))
}

// PhoneEQ applies the EQ predicate on the "Phone" field.
func PhoneEQ(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldEQ(FieldPhone, v))
}

// PhoneNEQ applies the NEQ predicate on the "Phone" field.
func PhoneNEQ(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldNEQ(FieldPhone, v))
}

// PhoneIn applies the In predicate on the "Phone" field.
func PhoneIn(vs ...string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldIn(FieldPhone, vs...))
}

// PhoneNotIn applies the NotIn predicate on the "Phone" field.
func PhoneNotIn(vs ...string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldNotIn(FieldPhone, vs...))
}

// PhoneGT applies the GT predicate on the "Phone" field.
func PhoneGT(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldGT(FieldPhone, v))
}

// PhoneGTE applies the GTE predicate on the "Phone" field.
func PhoneGTE(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldGTE(FieldPhone, v))
}

// PhoneLT applies the LT predicate on the "Phone" field.
func PhoneLT(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldLT(FieldPhone, v))
}

// PhoneLTE applies the LTE predicate on the "Phone" field.
func PhoneLTE(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldLTE(FieldPhone, v))
}

// PhoneContains applies the Contains predicate on the "Phone" field.
func PhoneContains(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldContains(FieldPhone, v))
}

// PhoneHasPrefix applies the HasPrefix predicate on the "Phone" field.
func PhoneHasPrefix(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldHasPrefix(FieldPhone, v))
}

// PhoneHasSuffix applies the HasSuffix predicate on the "Phone" field.
func PhoneHasSuffix(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldHasSuffix(FieldPhone, v))
}

// PhoneIsNil applies the IsNil predicate on the "Phone" field.
func PhoneIsNil() predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldIsNull(FieldPhone))
}

// PhoneNotNil applies the NotNil predicate on the "Phone" field.
func PhoneNotNil() predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldNotNull(FieldPhone))
}

// PhoneEqualFold applies the EqualFold predicate on the "Phone" field.
func PhoneEqualFold(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldEqualFold(FieldPhone, v))
}

// PhoneContainsFold applies the ContainsFold predicate on the "Phone" field.
func PhoneContainsFold(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldContainsFold(FieldPhone, v))
}

// EmailEQ applies the EQ predicate on the "Email" field.
func EmailEQ(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "Email" field.
func EmailNEQ(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "Email" field.
func EmailIn(vs ...string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "Email" field.
func EmailNotIn(vs ...string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "Email" field.
func EmailGT(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "Email" field.
func EmailGTE(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "Email" field.
func EmailLT(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "Email" field.
func EmailLTE(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "Email" field.
func EmailContains(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "Email" field.
func EmailHasPrefix(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "Email" field.
func EmailHasSuffix(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "Email" field.
func EmailIsNil() predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "Email" field.
func EmailNotNil() predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "Email" field.
func EmailEqualFold(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "Email" field.
func EmailContainsFold(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldContainsFold(FieldEmail, v))
}

// RoleEQ applies the EQ predicate on the "Role" field.
func RoleEQ(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "Role" field.
func RoleNEQ(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "Role" field.
func RoleIn(vs ...string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "Role" field.
func RoleNotIn(vs ...string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "Role" field.
func RoleGT(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "Role" field.
func RoleGTE(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "Role" field.
func RoleLT(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "Role" field.
func RoleLTE(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "Role" field.
func RoleContains(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "Role" field.
func RoleHasPrefix(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "Role" field.
func RoleHasSuffix(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldHasSuffix(FieldRole, v))
}

// RoleIsNil applies the IsNil predicate on the "Role" field.
func RoleIsNil() predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldIsNull(FieldRole))
}

// RoleNotNil applies the NotNil predicate on the "Role" field.
func RoleNotNil() predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldNotNull(FieldRole))
}

// RoleEqualFold applies the EqualFold predicate on the "Role" field.
func RoleEqualFold(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "Role" field.
func RoleContainsFold(v string) predicate.MemberSchema {
	return predicate.MemberSchema(sql.FieldContainsFold(FieldRole, v))
}

// HasClients applies the HasEdge predicate on the "clients" edge.
func HasClients() predicate.MemberSchema {
	return predicate.MemberSchema(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, ClientsTable, ClientsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClientsWith applies the HasEdge predicate on the "clients" edge with a given conditions (other predicates).
func HasClientsWith(preds ...predicate.ClientSchema) predicate.MemberSchema {
	return predicate.MemberSchema(func(s *sql.Selector) {
		step := newClientsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MemberSchema) predicate.MemberSchema {
	return predicate.MemberSchema(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MemberSchema) predicate.MemberSchema {
	return predicate.MemberSchema(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MemberSchema) predicate.MemberSchema {
	return predicate.MemberSchema(sql.NotPredicates(p))
}
