// Code generated by ent, DO NOT EDIT.

package clientschema

import (
	"client_service/internal/infrastructure/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldLTE(FieldID, id))
}

// ClientID applies equality check predicate on the "ClientID" field. It's identical to ClientIDEQ.
func ClientID(v int64) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldClientID, v))
}

// Name applies equality check predicate on the "Name" field. It's identical to NameEQ.
func Name(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldName, v))
}

// USCC applies equality check predicate on the "USCC" field. It's identical to USCCEQ.
func USCC(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldUSCC, v))
}

// Contact applies equality check predicate on the "Contact" field. It's identical to ContactEQ.
func Contact(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldContact, v))
}

// Phone applies equality check predicate on the "Phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldPhone, v))
}

// Email applies equality check predicate on the "Email" field. It's identical to EmailEQ.
func Email(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldEmail, v))
}

// Address applies equality check predicate on the "Address" field. It's identical to AddressEQ.
func Address(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldAddress, v))
}

// IsActive applies equality check predicate on the "IsActive" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAt applies equality check predicate on the "CreatedAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "UpdatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldUpdatedAt, v))
}

// ClientIDEQ applies the EQ predicate on the "ClientID" field.
func ClientIDEQ(v int64) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "ClientID" field.
func ClientIDNEQ(v int64) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "ClientID" field.
func ClientIDIn(vs ...int64) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "ClientID" field.
func ClientIDNotIn(vs ...int64) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "ClientID" field.
func ClientIDGT(v int64) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "ClientID" field.
func ClientIDGTE(v int64) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "ClientID" field.
func ClientIDLT(v int64) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "ClientID" field.
func ClientIDLTE(v int64) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldLTE(FieldClientID, v))
}

// NameEQ applies the EQ predicate on the "Name" field.
func NameEQ(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "Name" field.
func NameNEQ(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "Name" field.
func NameIn(vs ...string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "Name" field.
func NameNotIn(vs ...string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "Name" field.
func NameGT(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "Name" field.
func NameGTE(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "Name" field.
func NameLT(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "Name" field.
func NameLTE(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "Name" field.
func NameContains(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "Name" field.
func NameHasPrefix(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "Name" field.
func NameHasSuffix(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "Name" field.
func NameEqualFold(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "Name" field.
func NameContainsFold(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldContainsFold(FieldName, v))
}

// USCCEQ applies the EQ predicate on the "USCC" field.
func USCCEQ(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldUSCC, v))
}

// USCCNEQ applies the NEQ predicate on the "USCC" field.
func USCCNEQ(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNEQ(FieldUSCC, v))
}

// USCCIn applies the In predicate on the "USCC" field.
func USCCIn(vs ...string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldIn(FieldUSCC, vs...))
}

// USCCNotIn applies the NotIn predicate on the "USCC" field.
func USCCNotIn(vs ...string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNotIn(FieldUSCC, vs...))
}

// USCCGT applies the GT predicate on the "USCC" field.
func USCCGT(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldGT(FieldUSCC, v))
}

// USCCGTE applies the GTE predicate on the "USCC" field.
func USCCGTE(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldGTE(FieldUSCC, v))
}

// USCCLT applies the LT predicate on the "USCC" field.
func USCCLT(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldLT(FieldUSCC, v))
}

// USCCLTE applies the LTE predicate on the "USCC" field.
func USCCLTE(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldLTE(FieldUSCC, v))
}

// USCCContains applies the Contains predicate on the "USCC" field.
func USCCContains(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldContains(FieldUSCC, v))
}

// USCCHasPrefix applies the HasPrefix predicate on the "USCC" field.
func USCCHasPrefix(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldHasPrefix(FieldUSCC, v))
}

// USCCHasSuffix applies the HasSuffix predicate on the "USCC" field.
func USCCHasSuffix(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldHasSuffix(FieldUSCC, v))
}

// USCCEqualFold applies the EqualFold predicate on the "USCC" field.
func USCCEqualFold(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEqualFold(FieldUSCC, v))
}

// USCCContainsFold applies the ContainsFold predicate on the "USCC" field.
func USCCContainsFold(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldContainsFold(FieldUSCC, v))
}

// ContactEQ applies the EQ predicate on the "Contact" field.
func ContactEQ(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldContact, v))
}

// ContactNEQ applies the NEQ predicate on the "Contact" field.
func ContactNEQ(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNEQ(FieldContact, v))
}

// ContactIn applies the In predicate on the "Contact" field.
func ContactIn(vs ...string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldIn(FieldContact, vs...))
}

// ContactNotIn applies the NotIn predicate on the "Contact" field.
func ContactNotIn(vs ...string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNotIn(FieldContact, vs...))
}

// ContactGT applies the GT predicate on the "Contact" field.
func ContactGT(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldGT(FieldContact, v))
}

// ContactGTE applies the GTE predicate on the "Contact" field.
func ContactGTE(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldGTE(FieldContact, v))
}

// ContactLT applies the LT predicate on the "Contact" field.
func ContactLT(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldLT(FieldContact, v))
}

// ContactLTE applies the LTE predicate on the "Contact" field.
func ContactLTE(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldLTE(FieldContact, v))
}

// ContactContains applies the Contains predicate on the "Contact" field.
func ContactContains(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldContains(FieldContact, v))
}

// ContactHasPrefix applies the HasPrefix predicate on the "Contact" field.
func ContactHasPrefix(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldHasPrefix(FieldContact, v))
}

// ContactHasSuffix applies the HasSuffix predicate on the "Contact" field.
func ContactHasSuffix(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldHasSuffix(FieldContact, v))
}

// ContactEqualFold applies the EqualFold predicate on the "Contact" field.
func ContactEqualFold(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEqualFold(FieldContact, v))
}

// ContactContainsFold applies the ContainsFold predicate on the "Contact" field.
func ContactContainsFold(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldContainsFold(FieldContact, v))
}

// PhoneEQ applies the EQ predicate on the "Phone" field.
func PhoneEQ(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldPhone, v))
}

// PhoneNEQ applies the NEQ predicate on the "Phone" field.
func PhoneNEQ(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNEQ(FieldPhone, v))
}

// PhoneIn applies the In predicate on the "Phone" field.
func PhoneIn(vs ...string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldIn(FieldPhone, vs...))
}

// PhoneNotIn applies the NotIn predicate on the "Phone" field.
func PhoneNotIn(vs ...string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNotIn(FieldPhone, vs...))
}

// PhoneGT applies the GT predicate on the "Phone" field.
func PhoneGT(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldGT(FieldPhone, v))
}

// PhoneGTE applies the GTE predicate on the "Phone" field.
func PhoneGTE(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldGTE(FieldPhone, v))
}

// PhoneLT applies the LT predicate on the "Phone" field.
func PhoneLT(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldLT(FieldPhone, v))
}

// PhoneLTE applies the LTE predicate on the "Phone" field.
func PhoneLTE(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldLTE(FieldPhone, v))
}

// PhoneContains applies the Contains predicate on the "Phone" field.
func PhoneContains(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldContains(FieldPhone, v))
}

// PhoneHasPrefix applies the HasPrefix predicate on the "Phone" field.
func PhoneHasPrefix(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldHasPrefix(FieldPhone, v))
}

// PhoneHasSuffix applies the HasSuffix predicate on the "Phone" field.
func PhoneHasSuffix(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldHasSuffix(FieldPhone, v))
}

// PhoneEqualFold applies the EqualFold predicate on the "Phone" field.
func PhoneEqualFold(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEqualFold(FieldPhone, v))
}

// PhoneContainsFold applies the ContainsFold predicate on the "Phone" field.
func PhoneContainsFold(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldContainsFold(FieldPhone, v))
}

// EmailEQ applies the EQ predicate on the "Email" field.
func EmailEQ(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "Email" field.
func EmailNEQ(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "Email" field.
func EmailIn(vs ...string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "Email" field.
func EmailNotIn(vs ...string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "Email" field.
func EmailGT(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "Email" field.
func EmailGTE(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "Email" field.
func EmailLT(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "Email" field.
func EmailLTE(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "Email" field.
func EmailContains(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "Email" field.
func EmailHasPrefix(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "Email" field.
func EmailHasSuffix(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "Email" field.
func EmailEqualFold(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "Email" field.
func EmailContainsFold(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldContainsFold(FieldEmail, v))
}

// AddressEQ applies the EQ predicate on the "Address" field.
func AddressEQ(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "Address" field.
func AddressNEQ(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "Address" field.
func AddressIn(vs ...string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "Address" field.
func AddressNotIn(vs ...string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "Address" field.
func AddressGT(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "Address" field.
func AddressGTE(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "Address" field.
func AddressLT(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "Address" field.
func AddressLTE(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "Address" field.
func AddressContains(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "Address" field.
func AddressHasPrefix(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "Address" field.
func AddressHasSuffix(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "Address" field.
func AddressEqualFold(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "Address" field.
func AddressContainsFold(v string) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldContainsFold(FieldAddress, v))
}

// IsActiveEQ applies the EQ predicate on the "IsActive" field.
func IsActiveEQ(v bool) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "IsActive" field.
func IsActiveNEQ(v bool) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "CreatedAt" field.
func CreatedAtEQ(v time.Time) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "CreatedAt" field.
func CreatedAtNEQ(v time.Time) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "CreatedAt" field.
func CreatedAtIn(vs ...time.Time) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "CreatedAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "CreatedAt" field.
func CreatedAtGT(v time.Time) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "CreatedAt" field.
func CreatedAtGTE(v time.Time) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "CreatedAt" field.
func CreatedAtLT(v time.Time) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "CreatedAt" field.
func CreatedAtLTE(v time.Time) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "UpdatedAt" field.
func UpdatedAtEQ(v time.Time) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "UpdatedAt" field.
func UpdatedAtNEQ(v time.Time) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "UpdatedAt" field.
func UpdatedAtIn(vs ...time.Time) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "UpdatedAt" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "UpdatedAt" field.
func UpdatedAtGT(v time.Time) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "UpdatedAt" field.
func UpdatedAtGTE(v time.Time) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "UpdatedAt" field.
func UpdatedAtLT(v time.Time) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "UpdatedAt" field.
func UpdatedAtLTE(v time.Time) predicate.ClientSchema {
	return predicate.ClientSchema(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasMembers applies the HasEdge predicate on the "members" edge.
func HasMembers() predicate.ClientSchema {
	return predicate.ClientSchema(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, MembersTable, MembersPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMembersWith applies the HasEdge predicate on the "members" edge with a given conditions (other predicates).
func HasMembersWith(preds ...predicate.MemberSchema) predicate.ClientSchema {
	return predicate.ClientSchema(func(s *sql.Selector) {
		step := newMembersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ClientSchema) predicate.ClientSchema {
	return predicate.ClientSchema(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ClientSchema) predicate.ClientSchema {
	return predicate.ClientSchema(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ClientSchema) predicate.ClientSchema {
	return predicate.ClientSchema(sql.NotPredicates(p))
}
