// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ClientSchema is the predicate function for clientschema builders.
type ClientSchema func(*sql.Selector)
