// Code generated by ent, DO NOT EDIT.

package ent

import (
	"client_service/internal/infrastructure/ent/clientschema"
	"client_service/internal/infrastructure/ent/memberschema"
	"client_service/internal/infrastructure/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClientSchemaUpdate is the builder for updating ClientSchema entities.
type ClientSchemaUpdate struct {
	config
	hooks    []Hook
	mutation *ClientSchemaMutation
}

// Where appends a list predicates to the ClientSchemaUpdate builder.
func (_u *ClientSchemaUpdate) Where(ps ...predicate.ClientSchema) *ClientSchemaUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "Name" field.
func (_u *ClientSchemaUpdate) SetName(v string) *ClientSchemaUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (_u *ClientSchemaUpdate) SetNillableName(v *string) *ClientSchemaUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUSCC sets the "USCC" field.
func (_u *ClientSchemaUpdate) SetUSCC(v string) *ClientSchemaUpdate {
	_u.mutation.SetUSCC(v)
	return _u
}

// SetNillableUSCC sets the "USCC" field if the given value is not nil.
func (_u *ClientSchemaUpdate) SetNillableUSCC(v *string) *ClientSchemaUpdate {
	if v != nil {
		_u.SetUSCC(*v)
	}
	return _u
}

// SetContact sets the "Contact" field.
func (_u *ClientSchemaUpdate) SetContact(v string) *ClientSchemaUpdate {
	_u.mutation.SetContact(v)
	return _u
}

// SetNillableContact sets the "Contact" field if the given value is not nil.
func (_u *ClientSchemaUpdate) SetNillableContact(v *string) *ClientSchemaUpdate {
	if v != nil {
		_u.SetContact(*v)
	}
	return _u
}

// SetPhone sets the "Phone" field.
func (_u *ClientSchemaUpdate) SetPhone(v string) *ClientSchemaUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "Phone" field if the given value is not nil.
func (_u *ClientSchemaUpdate) SetNillablePhone(v *string) *ClientSchemaUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetEmail sets the "Email" field.
func (_u *ClientSchemaUpdate) SetEmail(v string) *ClientSchemaUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "Email" field if the given value is not nil.
func (_u *ClientSchemaUpdate) SetNillableEmail(v *string) *ClientSchemaUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetAddress sets the "Address" field.
func (_u *ClientSchemaUpdate) SetAddress(v string) *ClientSchemaUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "Address" field if the given value is not nil.
func (_u *ClientSchemaUpdate) SetNillableAddress(v *string) *ClientSchemaUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetIsActive sets the "IsActive" field.
func (_u *ClientSchemaUpdate) SetIsActive(v bool) *ClientSchemaUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "IsActive" field if the given value is not nil.
func (_u *ClientSchemaUpdate) SetNillableIsActive(v *bool) *ClientSchemaUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "UpdatedAt" field.
func (_u *ClientSchemaUpdate) SetUpdatedAt(v time.Time) *ClientSchemaUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddMemberIDs adds the "members" edge to the MemberSchema entity by IDs.
func (_u *ClientSchemaUpdate) AddMemberIDs(ids ...int) *ClientSchemaUpdate {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the MemberSchema entity.
func (_u *ClientSchemaUpdate) AddMembers(v ...*MemberSchema) *ClientSchemaUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// Mutation returns the ClientSchemaMutation object of the builder.
func (_u *ClientSchemaUpdate) Mutation() *ClientSchemaMutation {
	return _u.mutation
}

// ClearMembers clears all "members" edges to the MemberSchema entity.
func (_u *ClientSchemaUpdate) ClearMembers() *ClientSchemaUpdate {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to MemberSchema entities by IDs.
func (_u *ClientSchemaUpdate) RemoveMemberIDs(ids ...int) *ClientSchemaUpdate {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to MemberSchema entities.
func (_u *ClientSchemaUpdate) RemoveMembers(v ...*MemberSchema) *ClientSchemaUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ClientSchemaUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClientSchemaUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ClientSchemaUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClientSchemaUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ClientSchemaUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := clientschema.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClientSchemaUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := clientschema.NameValidator(v); err != nil {
			return &ValidationError{Name: "Name", err: fmt.Errorf(`ent: validator failed for field "ClientSchema.Name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.USCC(); ok {
		if err := clientschema.USCCValidator(v); err != nil {
			return &ValidationError{Name: "USCC", err: fmt.Errorf(`ent: validator failed for field "ClientSchema.USCC": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Contact(); ok {
		if err := clientschema.ContactValidator(v); err != nil {
			return &ValidationError{Name: "Contact", err: fmt.Errorf(`ent: validator failed for field "ClientSchema.Contact": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := clientschema.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "Phone", err: fmt.Errorf(`ent: validator failed for field "ClientSchema.Phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := clientschema.EmailValidator(v); err != nil {
			return &ValidationError{Name: "Email", err: fmt.Errorf(`ent: validator failed for field "ClientSchema.Email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := clientschema.AddressValidator(v); err != nil {
			return &ValidationError{Name: "Address", err: fmt.Errorf(`ent: validator failed for field "ClientSchema.Address": %w`, err)}
		}
	}
	return nil
}

func (_u *ClientSchemaUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clientschema.Table, clientschema.Columns, sqlgraph.NewFieldSpec(clientschema.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(clientschema.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.USCC(); ok {
		_spec.SetField(clientschema.FieldUSCC, field.TypeString, value)
	}
	if value, ok := _u.mutation.Contact(); ok {
		_spec.SetField(clientschema.FieldContact, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(clientschema.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(clientschema.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(clientschema.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(clientschema.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(clientschema.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   clientschema.MembersTable,
			Columns: clientschema.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberschema.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   clientschema.MembersTable,
			Columns: clientschema.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberschema.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   clientschema.MembersTable,
			Columns: clientschema.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberschema.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clientschema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ClientSchemaUpdateOne is the builder for updating a single ClientSchema entity.
type ClientSchemaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClientSchemaMutation
}

// SetName sets the "Name" field.
func (_u *ClientSchemaUpdateOne) SetName(v string) *ClientSchemaUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (_u *ClientSchemaUpdateOne) SetNillableName(v *string) *ClientSchemaUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUSCC sets the "USCC" field.
func (_u *ClientSchemaUpdateOne) SetUSCC(v string) *ClientSchemaUpdateOne {
	_u.mutation.SetUSCC(v)
	return _u
}

// SetNillableUSCC sets the "USCC" field if the given value is not nil.
func (_u *ClientSchemaUpdateOne) SetNillableUSCC(v *string) *ClientSchemaUpdateOne {
	if v != nil {
		_u.SetUSCC(*v)
	}
	return _u
}

// SetContact sets the "Contact" field.
func (_u *ClientSchemaUpdateOne) SetContact(v string) *ClientSchemaUpdateOne {
	_u.mutation.SetContact(v)
	return _u
}

// SetNillableContact sets the "Contact" field if the given value is not nil.
func (_u *ClientSchemaUpdateOne) SetNillableContact(v *string) *ClientSchemaUpdateOne {
	if v != nil {
		_u.SetContact(*v)
	}
	return _u
}

// SetPhone sets the "Phone" field.
func (_u *ClientSchemaUpdateOne) SetPhone(v string) *ClientSchemaUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "Phone" field if the given value is not nil.
func (_u *ClientSchemaUpdateOne) SetNillablePhone(v *string) *ClientSchemaUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetEmail sets the "Email" field.
func (_u *ClientSchemaUpdateOne) SetEmail(v string) *ClientSchemaUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "Email" field if the given value is not nil.
func (_u *ClientSchemaUpdateOne) SetNillableEmail(v *string) *ClientSchemaUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetAddress sets the "Address" field.
func (_u *ClientSchemaUpdateOne) SetAddress(v string) *ClientSchemaUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "Address" field if the given value is not nil.
func (_u *ClientSchemaUpdateOne) SetNillableAddress(v *string) *ClientSchemaUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetIsActive sets the "IsActive" field.
func (_u *ClientSchemaUpdateOne) SetIsActive(v bool) *ClientSchemaUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "IsActive" field if the given value is not nil.
func (_u *ClientSchemaUpdateOne) SetNillableIsActive(v *bool) *ClientSchemaUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "UpdatedAt" field.
func (_u *ClientSchemaUpdateOne) SetUpdatedAt(v time.Time) *ClientSchemaUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddMemberIDs adds the "members" edge to the MemberSchema entity by IDs.
func (_u *ClientSchemaUpdateOne) AddMemberIDs(ids ...int) *ClientSchemaUpdateOne {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the MemberSchema entity.
func (_u *ClientSchemaUpdateOne) AddMembers(v ...*MemberSchema) *ClientSchemaUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// Mutation returns the ClientSchemaMutation object of the builder.
func (_u *ClientSchemaUpdateOne) Mutation() *ClientSchemaMutation {
	return _u.mutation
}

// ClearMembers clears all "members" edges to the MemberSchema entity.
func (_u *ClientSchemaUpdateOne) ClearMembers() *ClientSchemaUpdateOne {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to MemberSchema entities by IDs.
func (_u *ClientSchemaUpdateOne) RemoveMemberIDs(ids ...int) *ClientSchemaUpdateOne {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to MemberSchema entities.
func (_u *ClientSchemaUpdateOne) RemoveMembers(v ...*MemberSchema) *ClientSchemaUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// Where appends a list predicates to the ClientSchemaUpdate builder.
func (_u *ClientSchemaUpdateOne) Where(ps ...predicate.ClientSchema) *ClientSchemaUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ClientSchemaUpdateOne) Select(field string, fields ...string) *ClientSchemaUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ClientSchema entity.
func (_u *ClientSchemaUpdateOne) Save(ctx context.Context) (*ClientSchema, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClientSchemaUpdateOne) SaveX(ctx context.Context) *ClientSchema {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ClientSchemaUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClientSchemaUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ClientSchemaUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := clientschema.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClientSchemaUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := clientschema.NameValidator(v); err != nil {
			return &ValidationError{Name: "Name", err: fmt.Errorf(`ent: validator failed for field "ClientSchema.Name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.USCC(); ok {
		if err := clientschema.USCCValidator(v); err != nil {
			return &ValidationError{Name: "USCC", err: fmt.Errorf(`ent: validator failed for field "ClientSchema.USCC": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Contact(); ok {
		if err := clientschema.ContactValidator(v); err != nil {
			return &ValidationError{Name: "Contact", err: fmt.Errorf(`ent: validator failed for field "ClientSchema.Contact": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := clientschema.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "Phone", err: fmt.Errorf(`ent: validator failed for field "ClientSchema.Phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := clientschema.EmailValidator(v); err != nil {
			return &ValidationError{Name: "Email", err: fmt.Errorf(`ent: validator failed for field "ClientSchema.Email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := clientschema.AddressValidator(v); err != nil {
			return &ValidationError{Name: "Address", err: fmt.Errorf(`ent: validator failed for field "ClientSchema.Address": %w`, err)}
		}
	}
	return nil
}

func (_u *ClientSchemaUpdateOne) sqlSave(ctx context.Context) (_node *ClientSchema, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clientschema.Table, clientschema.Columns, sqlgraph.NewFieldSpec(clientschema.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ClientSchema.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, clientschema.FieldID)
		for _, f := range fields {
			if !clientschema.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != clientschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(clientschema.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.USCC(); ok {
		_spec.SetField(clientschema.FieldUSCC, field.TypeString, value)
	}
	if value, ok := _u.mutation.Contact(); ok {
		_spec.SetField(clientschema.FieldContact, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(clientschema.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(clientschema.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(clientschema.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(clientschema.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(clientschema.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   clientschema.MembersTable,
			Columns: clientschema.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberschema.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   clientschema.MembersTable,
			Columns: clientschema.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberschema.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   clientschema.MembersTable,
			Columns: clientschema.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberschema.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ClientSchema{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clientschema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
