// Code generated by ent, DO NOT EDIT.

package ent

import (
	"client_service/internal/infrastructure/ent/clientschema"
	"client_service/internal/infrastructure/ent/memberschema"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClientSchemaCreate is the builder for creating a ClientSchema entity.
type ClientSchemaCreate struct {
	config
	mutation *ClientSchemaMutation
	hooks    []Hook
}

// SetClientID sets the "ClientID" field.
func (_c *ClientSchemaCreate) SetClientID(v int64) *ClientSchemaCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetName sets the "Name" field.
func (_c *ClientSchemaCreate) SetName(v string) *ClientSchemaCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetUSCC sets the "USCC" field.
func (_c *ClientSchemaCreate) SetUSCC(v string) *ClientSchemaCreate {
	_c.mutation.SetUSCC(v)
	return _c
}

// SetContact sets the "Contact" field.
func (_c *ClientSchemaCreate) SetContact(v string) *ClientSchemaCreate {
	_c.mutation.SetContact(v)
	return _c
}

// SetPhone sets the "Phone" field.
func (_c *ClientSchemaCreate) SetPhone(v string) *ClientSchemaCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetEmail sets the "Email" field.
func (_c *ClientSchemaCreate) SetEmail(v string) *ClientSchemaCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetAddress sets the "Address" field.
func (_c *ClientSchemaCreate) SetAddress(v string) *ClientSchemaCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetIsActive sets the "IsActive" field.
func (_c *ClientSchemaCreate) SetIsActive(v bool) *ClientSchemaCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "IsActive" field if the given value is not nil.
func (_c *ClientSchemaCreate) SetNillableIsActive(v *bool) *ClientSchemaCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "CreatedAt" field.
func (_c *ClientSchemaCreate) SetCreatedAt(v time.Time) *ClientSchemaCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "CreatedAt" field if the given value is not nil.
func (_c *ClientSchemaCreate) SetNillableCreatedAt(v *time.Time) *ClientSchemaCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "UpdatedAt" field.
func (_c *ClientSchemaCreate) SetUpdatedAt(v time.Time) *ClientSchemaCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "UpdatedAt" field if the given value is not nil.
func (_c *ClientSchemaCreate) SetNillableUpdatedAt(v *time.Time) *ClientSchemaCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddMemberIDs adds the "members" edge to the MemberSchema entity by IDs.
func (_c *ClientSchemaCreate) AddMemberIDs(ids ...int) *ClientSchemaCreate {
	_c.mutation.AddMemberIDs(ids...)
	return _c
}

// AddMembers adds the "members" edges to the MemberSchema entity.
func (_c *ClientSchemaCreate) AddMembers(v ...*MemberSchema) *ClientSchemaCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberIDs(ids...)
}

// Mutation returns the ClientSchemaMutation object of the builder.
func (_c *ClientSchemaCreate) Mutation() *ClientSchemaMutation {
	return _c.mutation
}

// Save creates the ClientSchema in the database.
func (_c *ClientSchemaCreate) Save(ctx context.Context) (*ClientSchema, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ClientSchemaCreate) SaveX(ctx context.Context) *ClientSchema {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClientSchemaCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClientSchemaCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ClientSchemaCreate) defaults() {
	if _, ok := _c.mutation.IsActive(); !ok {
		v := clientschema.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := clientschema.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := clientschema.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ClientSchemaCreate) check() error {
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "ClientID", err: errors.New(`ent: missing required field "ClientSchema.ClientID"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "Name", err: errors.New(`ent: missing required field "ClientSchema.Name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := clientschema.NameValidator(v); err != nil {
			return &ValidationError{Name: "Name", err: fmt.Errorf(`ent: validator failed for field "ClientSchema.Name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.USCC(); !ok {
		return &ValidationError{Name: "USCC", err: errors.New(`ent: missing required field "ClientSchema.USCC"`)}
	}
	if v, ok := _c.mutation.USCC(); ok {
		if err := clientschema.USCCValidator(v); err != nil {
			return &ValidationError{Name: "USCC", err: fmt.Errorf(`ent: validator failed for field "ClientSchema.USCC": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Contact(); !ok {
		return &ValidationError{Name: "Contact", err: errors.New(`ent: missing required field "ClientSchema.Contact"`)}
	}
	if v, ok := _c.mutation.Contact(); ok {
		if err := clientschema.ContactValidator(v); err != nil {
			return &ValidationError{Name: "Contact", err: fmt.Errorf(`ent: validator failed for field "ClientSchema.Contact": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Phone(); !ok {
		return &ValidationError{Name: "Phone", err: errors.New(`ent: missing required field "ClientSchema.Phone"`)}
	}
	if v, ok := _c.mutation.Phone(); ok {
		if err := clientschema.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "Phone", err: fmt.Errorf(`ent: validator failed for field "ClientSchema.Phone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "Email", err: errors.New(`ent: missing required field "ClientSchema.Email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := clientschema.EmailValidator(v); err != nil {
			return &ValidationError{Name: "Email", err: fmt.Errorf(`ent: validator failed for field "ClientSchema.Email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "Address", err: errors.New(`ent: missing required field "ClientSchema.Address"`)}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := clientschema.AddressValidator(v); err != nil {
			return &ValidationError{Name: "Address", err: fmt.Errorf(`ent: validator failed for field "ClientSchema.Address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "IsActive", err: errors.New(`ent: missing required field "ClientSchema.IsActive"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "CreatedAt", err: errors.New(`ent: missing required field "ClientSchema.CreatedAt"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "UpdatedAt", err: errors.New(`ent: missing required field "ClientSchema.UpdatedAt"`)}
	}
	return nil
}

func (_c *ClientSchemaCreate) sqlSave(ctx context.Context) (*ClientSchema, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ClientSchemaCreate) createSpec() (*ClientSchema, *sqlgraph.CreateSpec) {
	var (
		_node = &ClientSchema{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(clientschema.Table, sqlgraph.NewFieldSpec(clientschema.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(clientschema.FieldClientID, field.TypeInt64, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(clientschema.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.USCC(); ok {
		_spec.SetField(clientschema.FieldUSCC, field.TypeString, value)
		_node.USCC = value
	}
	if value, ok := _c.mutation.Contact(); ok {
		_spec.SetField(clientschema.FieldContact, field.TypeString, value)
		_node.Contact = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(clientschema.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(clientschema.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(clientschema.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(clientschema.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(clientschema.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(clientschema.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   clientschema.MembersTable,
			Columns: clientschema.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberschema.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ClientSchemaCreateBulk is the builder for creating many ClientSchema entities in bulk.
type ClientSchemaCreateBulk struct {
	config
	err      error
	builders []*ClientSchemaCreate
}

// Save creates the ClientSchema entities in the database.
func (_c *ClientSchemaCreateBulk) Save(ctx context.Context) ([]*ClientSchema, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ClientSchema, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClientSchemaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ClientSchemaCreateBulk) SaveX(ctx context.Context) []*ClientSchema {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClientSchemaCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClientSchemaCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
