// Code generated by ent, DO NOT EDIT.

package ent

import (
	"client_service/internal/infrastructure/ent/clientschema"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ClientSchema is the model entity for the ClientSchema schema.
type ClientSchema struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ClientID holds the value of the "ClientID" field.
	ClientID int64 `json:"ClientID,omitempty"`
	// Name holds the value of the "Name" field.
	Name string `json:"Name,omitempty"`
	// USCC holds the value of the "USCC" field.
	USCC string `json:"USCC,omitempty"`
	// Contact holds the value of the "Contact" field.
	Contact string `json:"Contact,omitempty"`
	// Phone holds the value of the "Phone" field.
	Phone string `json:"Phone,omitempty"`
	// Email holds the value of the "Email" field.
	Email string `json:"Email,omitempty"`
	// Address holds the value of the "Address" field.
	Address string `json:"Address,omitempty"`
	// IsActive holds the value of the "IsActive" field.
	IsActive bool `json:"IsActive,omitempty"`
	// CreatedAt holds the value of the "CreatedAt" field.
	CreatedAt time.Time `json:"CreatedAt,omitempty"`
	// UpdatedAt holds the value of the "UpdatedAt" field.
	UpdatedAt time.Time `json:"UpdatedAt,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ClientSchemaQuery when eager-loading is set.
	Edges        ClientSchemaEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ClientSchemaEdges holds the relations/edges for other nodes in the graph.
type ClientSchemaEdges struct {
	// Members holds the value of the members edge.
	Members []*MemberSchema `json:"members,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e ClientSchemaEdges) MembersOrErr() ([]*MemberSchema, error) {
	if e.loadedTypes[0] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ClientSchema) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case clientschema.FieldIsActive:
			values[i] = new(sql.NullBool)
		case clientschema.FieldID, clientschema.FieldClientID:
			values[i] = new(sql.NullInt64)
		case clientschema.FieldName, clientschema.FieldUSCC, clientschema.FieldContact, clientschema.FieldPhone, clientschema.FieldEmail, clientschema.FieldAddress:
			values[i] = new(sql.NullString)
		case clientschema.FieldCreatedAt, clientschema.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ClientSchema fields.
func (_m *ClientSchema) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case clientschema.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case clientschema.FieldClientID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ClientID", values[i])
			} else if value.Valid {
				_m.ClientID = value.Int64
			}
		case clientschema.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case clientschema.FieldUSCC:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field USCC", values[i])
			} else if value.Valid {
				_m.USCC = value.String
			}
		case clientschema.FieldContact:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Contact", values[i])
			} else if value.Valid {
				_m.Contact = value.String
			}
		case clientschema.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Phone", values[i])
			} else if value.Valid {
				_m.Phone = value.String
			}
		case clientschema.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case clientschema.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case clientschema.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field IsActive", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case clientschema.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field CreatedAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case clientschema.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field UpdatedAt", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ClientSchema.
// This includes values selected through modifiers, order, etc.
func (_m *ClientSchema) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMembers queries the "members" edge of the ClientSchema entity.
func (_m *ClientSchema) QueryMembers() *MemberSchemaQuery {
	return NewClientSchemaClient(_m.config).QueryMembers(_m)
}

// Update returns a builder for updating this ClientSchema.
// Note that you need to call ClientSchema.Unwrap() before calling this method if this ClientSchema
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ClientSchema) Update() *ClientSchemaUpdateOne {
	return NewClientSchemaClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ClientSchema entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ClientSchema) Unwrap() *ClientSchema {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ClientSchema is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ClientSchema) String() string {
	var builder strings.Builder
	builder.WriteString("ClientSchema(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ClientID=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClientID))
	builder.WriteString(", ")
	builder.WriteString("Name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("USCC=")
	builder.WriteString(_m.USCC)
	builder.WriteString(", ")
	builder.WriteString("Contact=")
	builder.WriteString(_m.Contact)
	builder.WriteString(", ")
	builder.WriteString("Phone=")
	builder.WriteString(_m.Phone)
	builder.WriteString(", ")
	builder.WriteString("Email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("Address=")
	builder.WriteString(_m.Address)
	builder.WriteString(", ")
	builder.WriteString("IsActive=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("CreatedAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("UpdatedAt=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ClientSchemas is a parsable slice of ClientSchema.
type ClientSchemas []*ClientSchema
