// Code generated by ent, DO NOT EDIT.

package ent

import (
	"client_service/internal/infrastructure/ent/clientschema"
	"client_service/internal/infrastructure/ent/memberschema"
	"client_service/internal/infrastructure/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemberSchemaUpdate is the builder for updating MemberSchema entities.
type MemberSchemaUpdate struct {
	config
	hooks    []Hook
	mutation *MemberSchemaMutation
}

// Where appends a list predicates to the MemberSchemaUpdate builder.
func (_u *MemberSchemaUpdate) Where(ps ...predicate.MemberSchema) *MemberSchemaUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "Name" field.
func (_u *MemberSchemaUpdate) SetName(v string) *MemberSchemaUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (_u *MemberSchemaUpdate) SetNillableName(v *string) *MemberSchemaUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPhone sets the "Phone" field.
func (_u *MemberSchemaUpdate) SetPhone(v string) *MemberSchemaUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "Phone" field if the given value is not nil.
func (_u *MemberSchemaUpdate) SetNillablePhone(v *string) *MemberSchemaUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "Phone" field.
func (_u *MemberSchemaUpdate) ClearPhone() *MemberSchemaUpdate {
	_u.mutation.ClearPhone()
	return _u
}

// SetEmail sets the "Email" field.
func (_u *MemberSchemaUpdate) SetEmail(v string) *MemberSchemaUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "Email" field if the given value is not nil.
func (_u *MemberSchemaUpdate) SetNillableEmail(v *string) *MemberSchemaUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "Email" field.
func (_u *MemberSchemaUpdate) ClearEmail() *MemberSchemaUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetRole sets the "Role" field.
func (_u *MemberSchemaUpdate) SetRole(v string) *MemberSchemaUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "Role" field if the given value is not nil.
func (_u *MemberSchemaUpdate) SetNillableRole(v *string) *MemberSchemaUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// ClearRole clears the value of the "Role" field.
func (_u *MemberSchemaUpdate) ClearRole() *MemberSchemaUpdate {
	_u.mutation.ClearRole()
	return _u
}

// AddClientIDs adds the "clients" edge to the ClientSchema entity by IDs.
func (_u *MemberSchemaUpdate) AddClientIDs(ids ...int) *MemberSchemaUpdate {
	_u.mutation.AddClientIDs(ids...)
	return _u
}

// AddClients adds the "clients" edges to the ClientSchema entity.
func (_u *MemberSchemaUpdate) AddClients(v ...*ClientSchema) *MemberSchemaUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClientIDs(ids...)
}

// Mutation returns the MemberSchemaMutation object of the builder.
func (_u *MemberSchemaUpdate) Mutation() *MemberSchemaMutation {
	return _u.mutation
}

// ClearClients clears all "clients" edges to the ClientSchema entity.
func (_u *MemberSchemaUpdate) ClearClients() *MemberSchemaUpdate {
	_u.mutation.ClearClients()
	return _u
}

// RemoveClientIDs removes the "clients" edge to ClientSchema entities by IDs.
func (_u *MemberSchemaUpdate) RemoveClientIDs(ids ...int) *MemberSchemaUpdate {
	_u.mutation.RemoveClientIDs(ids...)
	return _u
}

// RemoveClients removes "clients" edges to ClientSchema entities.
func (_u *MemberSchemaUpdate) RemoveClients(v ...*ClientSchema) *MemberSchemaUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClientIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MemberSchemaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberSchemaUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MemberSchemaUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberSchemaUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberSchemaUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := memberschema.NameValidator(v); err != nil {
			return &ValidationError{Name: "Name", err: fmt.Errorf(`ent: validator failed for field "MemberSchema.Name": %w`, err)}
		}
	}
	return nil
}

func (_u *MemberSchemaUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memberschema.Table, memberschema.Columns, sqlgraph.NewFieldSpec(memberschema.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(memberschema.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(memberschema.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(memberschema.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(memberschema.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(memberschema.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(memberschema.FieldRole, field.TypeString, value)
	}
	if _u.mutation.RoleCleared() {
		_spec.ClearField(memberschema.FieldRole, field.TypeString)
	}
	if _u.mutation.ClientsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   memberschema.ClientsTable,
			Columns: memberschema.ClientsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientschema.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClientsIDs(); len(nodes) > 0 && !_u.mutation.ClientsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   memberschema.ClientsTable,
			Columns: memberschema.ClientsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientschema.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   memberschema.ClientsTable,
			Columns: memberschema.ClientsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientschema.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memberschema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MemberSchemaUpdateOne is the builder for updating a single MemberSchema entity.
type MemberSchemaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemberSchemaMutation
}

// SetName sets the "Name" field.
func (_u *MemberSchemaUpdateOne) SetName(v string) *MemberSchemaUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (_u *MemberSchemaUpdateOne) SetNillableName(v *string) *MemberSchemaUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPhone sets the "Phone" field.
func (_u *MemberSchemaUpdateOne) SetPhone(v string) *MemberSchemaUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "Phone" field if the given value is not nil.
func (_u *MemberSchemaUpdateOne) SetNillablePhone(v *string) *MemberSchemaUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "Phone" field.
func (_u *MemberSchemaUpdateOne) ClearPhone() *MemberSchemaUpdateOne {
	_u.mutation.ClearPhone()
	return _u
}

// SetEmail sets the "Email" field.
func (_u *MemberSchemaUpdateOne) SetEmail(v string) *MemberSchemaUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "Email" field if the given value is not nil.
func (_u *MemberSchemaUpdateOne) SetNillableEmail(v *string) *MemberSchemaUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "Email" field.
func (_u *MemberSchemaUpdateOne) ClearEmail() *MemberSchemaUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetRole sets the "Role" field.
func (_u *MemberSchemaUpdateOne) SetRole(v string) *MemberSchemaUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "Role" field if the given value is not nil.
func (_u *MemberSchemaUpdateOne) SetNillableRole(v *string) *MemberSchemaUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// ClearRole clears the value of the "Role" field.
func (_u *MemberSchemaUpdateOne) ClearRole() *MemberSchemaUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// AddClientIDs adds the "clients" edge to the ClientSchema entity by IDs.
func (_u *MemberSchemaUpdateOne) AddClientIDs(ids ...int) *MemberSchemaUpdateOne {
	_u.mutation.AddClientIDs(ids...)
	return _u
}

// AddClients adds the "clients" edges to the ClientSchema entity.
func (_u *MemberSchemaUpdateOne) AddClients(v ...*ClientSchema) *MemberSchemaUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClientIDs(ids...)
}

// Mutation returns the MemberSchemaMutation object of the builder.
func (_u *MemberSchemaUpdateOne) Mutation() *MemberSchemaMutation {
	return _u.mutation
}

// ClearClients clears all "clients" edges to the ClientSchema entity.
func (_u *MemberSchemaUpdateOne) ClearClients() *MemberSchemaUpdateOne {
	_u.mutation.ClearClients()
	return _u
}

// RemoveClientIDs removes the "clients" edge to ClientSchema entities by IDs.
func (_u *MemberSchemaUpdateOne) RemoveClientIDs(ids ...int) *MemberSchemaUpdateOne {
	_u.mutation.RemoveClientIDs(ids...)
	return _u
}

// RemoveClients removes "clients" edges to ClientSchema entities.
func (_u *MemberSchemaUpdateOne) RemoveClients(v ...*ClientSchema) *MemberSchemaUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClientIDs(ids...)
}

// Where appends a list predicates to the MemberSchemaUpdate builder.
func (_u *MemberSchemaUpdateOne) Where(ps ...predicate.MemberSchema) *MemberSchemaUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MemberSchemaUpdateOne) Select(field string, fields ...string) *MemberSchemaUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MemberSchema entity.
func (_u *MemberSchemaUpdateOne) Save(ctx context.Context) (*MemberSchema, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberSchemaUpdateOne) SaveX(ctx context.Context) *MemberSchema {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MemberSchemaUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberSchemaUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberSchemaUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := memberschema.NameValidator(v); err != nil {
			return &ValidationError{Name: "Name", err: fmt.Errorf(`ent: validator failed for field "MemberSchema.Name": %w`, err)}
		}
	}
	return nil
}

func (_u *MemberSchemaUpdateOne) sqlSave(ctx context.Context) (_node *MemberSchema, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memberschema.Table, memberschema.Columns, sqlgraph.NewFieldSpec(memberschema.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MemberSchema.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memberschema.FieldID)
		for _, f := range fields {
			if !memberschema.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != memberschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(memberschema.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(memberschema.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(memberschema.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(memberschema.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(memberschema.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(memberschema.FieldRole, field.TypeString, value)
	}
	if _u.mutation.RoleCleared() {
		_spec.ClearField(memberschema.FieldRole, field.TypeString)
	}
	if _u.mutation.ClientsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   memberschema.ClientsTable,
			Columns: memberschema.ClientsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientschema.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClientsIDs(); len(nodes) > 0 && !_u.mutation.ClientsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   memberschema.ClientsTable,
			Columns: memberschema.ClientsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientschema.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   memberschema.ClientsTable,
			Columns: memberschema.ClientsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientschema.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MemberSchema{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memberschema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
