// Code generated by ent, DO NOT EDIT.

package ent

import (
	"client_service/internal/infrastructure/ent/clientschema"
	"client_service/internal/infrastructure/ent/memberschema"
	"client_service/internal/infrastructure/ent/predicate"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemberSchemaQuery is the builder for querying MemberSchema entities.
type MemberSchemaQuery struct {
	config
	ctx         *QueryContext
	order       []memberschema.OrderOption
	inters      []Interceptor
	predicates  []predicate.MemberSchema
	withClients *ClientSchemaQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MemberSchemaQuery builder.
func (_q *MemberSchemaQuery) Where(ps ...predicate.MemberSchema) *MemberSchemaQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *MemberSchemaQuery) Limit(limit int) *MemberSchemaQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *MemberSchemaQuery) Offset(offset int) *MemberSchemaQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *MemberSchemaQuery) Unique(unique bool) *MemberSchemaQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *MemberSchemaQuery) Order(o ...memberschema.OrderOption) *MemberSchemaQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryClients chains the current query on the "clients" edge.
func (_q *MemberSchemaQuery) QueryClients() *ClientSchemaQuery {
	query := (&ClientSchemaClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(memberschema.Table, memberschema.FieldID, selector),
			sqlgraph.To(clientschema.Table, clientschema.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, memberschema.ClientsTable, memberschema.ClientsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MemberSchema entity from the query.
// Returns a *NotFoundError when no MemberSchema was found.
func (_q *MemberSchemaQuery) First(ctx context.Context) (*MemberSchema, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{memberschema.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *MemberSchemaQuery) FirstX(ctx context.Context) *MemberSchema {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MemberSchema ID from the query.
// Returns a *NotFoundError when no MemberSchema ID was found.
func (_q *MemberSchemaQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{memberschema.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *MemberSchemaQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MemberSchema entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MemberSchema entity is found.
// Returns a *NotFoundError when no MemberSchema entities are found.
func (_q *MemberSchemaQuery) Only(ctx context.Context) (*MemberSchema, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{memberschema.Label}
	default:
		return nil, &NotSingularError{memberschema.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *MemberSchemaQuery) OnlyX(ctx context.Context) *MemberSchema {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MemberSchema ID in the query.
// Returns a *NotSingularError when more than one MemberSchema ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *MemberSchemaQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{memberschema.Label}
	default:
		err = &NotSingularError{memberschema.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *MemberSchemaQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MemberSchemas.
func (_q *MemberSchemaQuery) All(ctx context.Context) ([]*MemberSchema, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MemberSchema, *MemberSchemaQuery]()
	return withInterceptors[[]*MemberSchema](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *MemberSchemaQuery) AllX(ctx context.Context) []*MemberSchema {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MemberSchema IDs.
func (_q *MemberSchemaQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(memberschema.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *MemberSchemaQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *MemberSchemaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*MemberSchemaQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *MemberSchemaQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *MemberSchemaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *MemberSchemaQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MemberSchemaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *MemberSchemaQuery) Clone() *MemberSchemaQuery {
	if _q == nil {
		return nil
	}
	return &MemberSchemaQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]memberschema.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.MemberSchema{}, _q.predicates...),
		withClients: _q.withClients.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithClients tells the query-builder to eager-load the nodes that are connected to
// the "clients" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MemberSchemaQuery) WithClients(opts ...func(*ClientSchemaQuery)) *MemberSchemaQuery {
	query := (&ClientSchemaClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withClients = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MemberID int64 `json:"MemberID,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MemberSchema.Query().
//		GroupBy(memberschema.FieldMemberID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *MemberSchemaQuery) GroupBy(field string, fields ...string) *MemberSchemaGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MemberSchemaGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = memberschema.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MemberID int64 `json:"MemberID,omitempty"`
//	}
//
//	client.MemberSchema.Query().
//		Select(memberschema.FieldMemberID).
//		Scan(ctx, &v)
func (_q *MemberSchemaQuery) Select(fields ...string) *MemberSchemaSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &MemberSchemaSelect{MemberSchemaQuery: _q}
	sbuild.label = memberschema.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MemberSchemaSelect configured with the given aggregations.
func (_q *MemberSchemaQuery) Aggregate(fns ...AggregateFunc) *MemberSchemaSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *MemberSchemaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !memberschema.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *MemberSchemaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MemberSchema, error) {
	var (
		nodes       = []*MemberSchema{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withClients != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MemberSchema).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MemberSchema{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withClients; query != nil {
		if err := _q.loadClients(ctx, query, nodes,
			func(n *MemberSchema) { n.Edges.Clients = []*ClientSchema{} },
			func(n *MemberSchema, e *ClientSchema) { n.Edges.Clients = append(n.Edges.Clients, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *MemberSchemaQuery) loadClients(ctx context.Context, query *ClientSchemaQuery, nodes []*MemberSchema, init func(*MemberSchema), assign func(*MemberSchema, *ClientSchema)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*MemberSchema)
	nids := make(map[int]map[*MemberSchema]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(memberschema.ClientsTable)
		s.Join(joinT).On(s.C(clientschema.FieldID), joinT.C(memberschema.ClientsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(memberschema.ClientsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(memberschema.ClientsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*MemberSchema]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*ClientSchema](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "clients" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (_q *MemberSchemaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *MemberSchemaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(memberschema.Table, memberschema.Columns, sqlgraph.NewFieldSpec(memberschema.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memberschema.FieldID)
		for i := range fields {
			if fields[i] != memberschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *MemberSchemaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(memberschema.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = memberschema.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MemberSchemaGroupBy is the group-by builder for MemberSchema entities.
type MemberSchemaGroupBy struct {
	selector
	build *MemberSchemaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *MemberSchemaGroupBy) Aggregate(fns ...AggregateFunc) *MemberSchemaGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *MemberSchemaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MemberSchemaQuery, *MemberSchemaGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *MemberSchemaGroupBy) sqlScan(ctx context.Context, root *MemberSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MemberSchemaSelect is the builder for selecting fields of MemberSchema entities.
type MemberSchemaSelect struct {
	*MemberSchemaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *MemberSchemaSelect) Aggregate(fns ...AggregateFunc) *MemberSchemaSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *MemberSchemaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MemberSchemaQuery, *MemberSchemaSelect](ctx, _s.MemberSchemaQuery, _s, _s.inters, v)
}

func (_s *MemberSchemaSelect) sqlScan(ctx context.Context, root *MemberSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
