// Code generated by ent, DO NOT EDIT.

package ent

import (
	"client_service/internal/infrastructure/ent/clientschema"
	"client_service/internal/infrastructure/ent/memberschema"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemberSchemaCreate is the builder for creating a MemberSchema entity.
type MemberSchemaCreate struct {
	config
	mutation *MemberSchemaMutation
	hooks    []Hook
}

// SetMemberID sets the "MemberID" field.
func (_c *MemberSchemaCreate) SetMemberID(v int64) *MemberSchemaCreate {
	_c.mutation.SetMemberID(v)
	return _c
}

// SetName sets the "Name" field.
func (_c *MemberSchemaCreate) SetName(v string) *MemberSchemaCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPhone sets the "Phone" field.
func (_c *MemberSchemaCreate) SetPhone(v string) *MemberSchemaCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetNillablePhone sets the "Phone" field if the given value is not nil.
func (_c *MemberSchemaCreate) SetNillablePhone(v *string) *MemberSchemaCreate {
	if v != nil {
		_c.SetPhone(*v)
	}
	return _c
}

// SetEmail sets the "Email" field.
func (_c *MemberSchemaCreate) SetEmail(v string) *MemberSchemaCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "Email" field if the given value is not nil.
func (_c *MemberSchemaCreate) SetNillableEmail(v *string) *MemberSchemaCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetRole sets the "Role" field.
func (_c *MemberSchemaCreate) SetRole(v string) *MemberSchemaCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "Role" field if the given value is not nil.
func (_c *MemberSchemaCreate) SetNillableRole(v *string) *MemberSchemaCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// AddClientIDs adds the "clients" edge to the ClientSchema entity by IDs.
func (_c *MemberSchemaCreate) AddClientIDs(ids ...int) *MemberSchemaCreate {
	_c.mutation.AddClientIDs(ids...)
	return _c
}

// AddClients adds the "clients" edges to the ClientSchema entity.
func (_c *MemberSchemaCreate) AddClients(v ...*ClientSchema) *MemberSchemaCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddClientIDs(ids...)
}

// Mutation returns the MemberSchemaMutation object of the builder.
func (_c *MemberSchemaCreate) Mutation() *MemberSchemaMutation {
	return _c.mutation
}

// Save creates the MemberSchema in the database.
func (_c *MemberSchemaCreate) Save(ctx context.Context) (*MemberSchema, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemberSchemaCreate) SaveX(ctx context.Context) *MemberSchema {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemberSchemaCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemberSchemaCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemberSchemaCreate) check() error {
	if _, ok := _c.mutation.MemberID(); !ok {
		return &ValidationError{Name: "MemberID", err: errors.New(`ent: missing required field "MemberSchema.MemberID"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "Name", err: errors.New(`ent: missing required field "MemberSchema.Name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := memberschema.NameValidator(v); err != nil {
			return &ValidationError{Name: "Name", err: fmt.Errorf(`ent: validator failed for field "MemberSchema.Name": %w`, err)}
		}
	}
	return nil
}

func (_c *MemberSchemaCreate) sqlSave(ctx context.Context) (*MemberSchema, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemberSchemaCreate) createSpec() (*MemberSchema, *sqlgraph.CreateSpec) {
	var (
		_node = &MemberSchema{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(memberschema.Table, sqlgraph.NewFieldSpec(memberschema.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.MemberID(); ok {
		_spec.SetField(memberschema.FieldMemberID, field.TypeInt64, value)
		_node.MemberID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(memberschema.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(memberschema.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(memberschema.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(memberschema.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if nodes := _c.mutation.ClientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   memberschema.ClientsTable,
			Columns: memberschema.ClientsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientschema.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MemberSchemaCreateBulk is the builder for creating many MemberSchema entities in bulk.
type MemberSchemaCreateBulk struct {
	config
	err      error
	builders []*MemberSchemaCreate
}

// Save creates the MemberSchema entities in the database.
func (_c *MemberSchemaCreateBulk) Save(ctx context.Context) ([]*MemberSchema, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MemberSchema, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemberSchemaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemberSchemaCreateBulk) SaveX(ctx context.Context) []*MemberSchema {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemberSchemaCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemberSchemaCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
