// Code generated by ent, DO NOT EDIT.

package ent

import (
	"client_service/internal/infrastructure/ent/memberschema"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// MemberSchema is the model entity for the MemberSchema schema.
type MemberSchema struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// MemberID holds the value of the "MemberID" field.
	MemberID int64 `json:"MemberID,omitempty"`
	// Name holds the value of the "Name" field.
	Name string `json:"Name,omitempty"`
	// Phone holds the value of the "Phone" field.
	Phone string `json:"Phone,omitempty"`
	// Email holds the value of the "Email" field.
	Email string `json:"Email,omitempty"`
	// Role holds the value of the "Role" field.
	Role string `json:"Role,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MemberSchemaQuery when eager-loading is set.
	Edges        MemberSchemaEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MemberSchemaEdges holds the relations/edges for other nodes in the graph.
type MemberSchemaEdges struct {
	// Clients holds the value of the clients edge.
	Clients []*ClientSchema `json:"clients,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ClientsOrErr returns the Clients value or an error if the edge
// was not loaded in eager-loading.
func (e MemberSchemaEdges) ClientsOrErr() ([]*ClientSchema, error) {
	if e.loadedTypes[0] {
		return e.Clients, nil
	}
	return nil, &NotLoadedError{edge: "clients"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MemberSchema) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case memberschema.FieldID, memberschema.FieldMemberID:
			values[i] = new(sql.NullInt64)
		case memberschema.FieldName, memberschema.FieldPhone, memberschema.FieldEmail, memberschema.FieldRole:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MemberSchema fields.
func (_m *MemberSchema) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case memberschema.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case memberschema.FieldMemberID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field MemberID", values[i])
			} else if value.Valid {
				_m.MemberID = value.Int64
			}
		case memberschema.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case memberschema.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Phone", values[i])
			} else if value.Valid {
				_m.Phone = value.String
			}
		case memberschema.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case memberschema.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MemberSchema.
// This includes values selected through modifiers, order, etc.
func (_m *MemberSchema) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryClients queries the "clients" edge of the MemberSchema entity.
func (_m *MemberSchema) QueryClients() *ClientSchemaQuery {
	return NewMemberSchemaClient(_m.config).QueryClients(_m)
}

// Update returns a builder for updating this MemberSchema.
// Note that you need to call MemberSchema.Unwrap() before calling this method if this MemberSchema
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MemberSchema) Update() *MemberSchemaUpdateOne {
	return NewMemberSchemaClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MemberSchema entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MemberSchema) Unwrap() *MemberSchema {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MemberSchema is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MemberSchema) String() string {
	var builder strings.Builder
	builder.WriteString("MemberSchema(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("MemberID=")
	builder.WriteString(fmt.Sprintf("%v", _m.MemberID))
	builder.WriteString(", ")
	builder.WriteString("Name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("Phone=")
	builder.WriteString(_m.Phone)
	builder.WriteString(", ")
	builder.WriteString("Email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("Role=")
	builder.WriteString(_m.Role)
	builder.WriteByte(')')
	return builder.String()
}

// MemberSchemas is a parsable slice of MemberSchema.
type MemberSchemas []*MemberSchema
