// Code generated by ent, DO NOT EDIT.

package ent

import (
	"client_service/internal/infrastructure/ent/clientschema"
	"client_service/internal/infrastructure/ent/memberschema"
	"client_service/internal/infrastructure/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	clientschemaFields := schema.ClientSchema{}.Fields()
	_ = clientschemaFields
	// clientschemaDescName is the schema descriptor for Name field.
	clientschemaDescName := clientschemaFields[1].Descriptor()
	// clientschema.NameValidator is a validator for the "Name" field. It is called by the builders before save.
	clientschema.NameValidator = clientschemaDescName.Validators[0].(func(string) error)
	// clientschemaDescUSCC is the schema descriptor for USCC field.
	clientschemaDescUSCC := clientschemaFields[2].Descriptor()
	// clientschema.USCCValidator is a validator for the "USCC" field. It is called by the builders before save.
	clientschema.USCCValidator = clientschemaDescUSCC.Validators[0].(func(string) error)
	// clientschemaDescContact is the schema descriptor for Contact field.
	clientschemaDescContact := clientschemaFields[3].Descriptor()
	// clientschema.ContactValidator is a validator for the "Contact" field. It is called by the builders before save.
	clientschema.ContactValidator = clientschemaDescContact.Validators[0].(func(string) error)
	// clientschemaDescPhone is the schema descriptor for Phone field.
	clientschemaDescPhone := clientschemaFields[4].Descriptor()
	// clientschema.PhoneValidator is a validator for the "Phone" field. It is called by the builders before save.
	clientschema.PhoneValidator = clientschemaDescPhone.Validators[0].(func(string) error)
	// clientschemaDescEmail is the schema descriptor for Email field.
	clientschemaDescEmail := clientschemaFields[5].Descriptor()
	// clientschema.EmailValidator is a validator for the "Email" field. It is called by the builders before save.
	clientschema.EmailValidator = clientschemaDescEmail.Validators[0].(func(string) error)
	// clientschemaDescAddress is the schema descriptor for Address field.
	clientschemaDescAddress := clientschemaFields[6].Descriptor()
	// clientschema.AddressValidator is a validator for the "Address" field. It is called by the builders before save.
	clientschema.AddressValidator = clientschemaDescAddress.Validators[0].(func(string) error)
	// clientschemaDescIsActive is the schema descriptor for IsActive field.
	clientschemaDescIsActive := clientschemaFields[7].Descriptor()
	// clientschema.DefaultIsActive holds the default value on creation for the IsActive field.
	clientschema.DefaultIsActive = clientschemaDescIsActive.Default.(bool)
	// clientschemaDescCreatedAt is the schema descriptor for CreatedAt field.
	clientschemaDescCreatedAt := clientschemaFields[8].Descriptor()
	// clientschema.DefaultCreatedAt holds the default value on creation for the CreatedAt field.
	clientschema.DefaultCreatedAt = clientschemaDescCreatedAt.Default.(func() time.Time)
	// clientschemaDescUpdatedAt is the schema descriptor for UpdatedAt field.
	clientschemaDescUpdatedAt := clientschemaFields[9].Descriptor()
	// clientschema.DefaultUpdatedAt holds the default value on creation for the UpdatedAt field.
	clientschema.DefaultUpdatedAt = clientschemaDescUpdatedAt.Default.(func() time.Time)
	// clientschema.UpdateDefaultUpdatedAt holds the default value on update for the UpdatedAt field.
	clientschema.UpdateDefaultUpdatedAt = clientschemaDescUpdatedAt.UpdateDefault.(func() time.Time)
	memberschemaFields := schema.MemberSchema{}.Fields()
	_ = memberschemaFields
	// memberschemaDescName is the schema descriptor for Name field.
	memberschemaDescName := memberschemaFields[1].Descriptor()
	// memberschema.NameValidator is a validator for the "Name" field. It is called by the builders before save.
	memberschema.NameValidator = memberschemaDescName.Validators[0].(func(string) error)
}
