// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ClientSchemasColumns holds the columns for the "client_schemas" table.
	ClientSchemasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "client_id", Type: field.TypeInt64, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "uscc", Type: field.TypeString, Unique: true},
		{Name: "contact", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "address", Type: field.TypeString},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ClientSchemasTable holds the schema information for the "client_schemas" table.
	ClientSchemasTable = &schema.Table{
		Name:       "client_schemas",
		Columns:    ClientSchemasColumns,
		PrimaryKey: []*schema.Column{ClientSchemasColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ClientSchemasTable,
	}
)

func init() {
}
